; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:freenove_esp32_s3_wroom]
platform = espressif32 @ ^6.0.1
board = freenove_esp32_s3_wroom
framework = espidf
monitor_speed = 115200
board_build.partitions = partitions.csv
build_flags = 
    -D CONFIG_TINYUSB_HID_ENABLED=1
    -D CONFIG_TINYUSB_DESC_HID_STRING="G27 Racing Wheel"
    -D CONFIG_USB_DESC_MANUFACTURER_STRING="Logitech"
    -D CONFIG_USB_DESC_PRODUCT_STRING="G27 Racing Wheel"
    -D CONFIG_USB_DESC_PRODUCT_REVISION="1.0"
    -D CONFIG_USB_DESC_BCDDEVICE=0x0100
lib_deps = madhephaestus/ESP32Encoder@^0.11.7

# Add these lines to tell PlatformIO where to find your source files
src_dir = main
